name: CI

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install
      run: yarn install

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build

    - name: Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOOT_MINTS_ON_THE_PROON_1 }}'
        channelId: live
        projectId: foot-mints-on-the-proon-1
